### ISSUE TITLE
Host user www-data may not have cap_net_bind_service

### ISSUE THREAD

**Issue by JVMerkle** [JVMerkle/TS3-Ranksystem#2]
The user `www-data` may not have `cap_net_bind_service` on the host system to bind port 80. 

**Solution:** Offer an environment variable to change the port (e.g. to 8080).

@201508876PMH

**Comment by JVMerkle** [comment]
Fixed with 3daa9e6a2e822392e63a70ed09c53dc46bf58090 by setting cap_net_bind_service on apache2.

**Comment by 201508876PMH** [comment]
Ill give it a shot! I'll write back shortly :)

Den ons. 17. feb. 2021 kl. 16.41 skrev Julian Merkle <
notifications@github.com>:
