### ISSUE TITLE
URL in verify link contains internal IP / Port

### ISSUE THREAD

**Issue by LickABrick** [JVMerkle/TS3-Ranksystem#3]
Currently when you verify you get a message in TS3, the message contains the internal IP / Port of the server e.g. http://172.16.10.1:8080.

It would be nice to have an env variable to control the external fqdn of the server so you can override this.

**Comment by JVMerkle** [comment]
Hey LickABrick,

if I am not mistaken the link in the TS3 message is built here: https://github.com/JVMerkle/TS3-Ranksystem/blob/9750be7917682cf0b26cd58475c4c9df15ceb702/stats/verify.php#L102
This depends on how you visit the website. Did you request the verification via `http://172.16.10.1:8080`?

**Comment by JVMerkle** [comment]
Glad to hear that!

Yeah I noticed the https part in my installation as well :/
